openapi: "3.0.0"

info:
  title: "Ash API"
  version: "0.0.1"

servers:
  - url: "/api/v0"

paths:
  "/info":
    get:
      operationId: "thoth.ash.api.info_get"
      tags:
        - "info"
      summary: "Get some information about this API."
      responses:
        "200":
          description: "Successful response with information."